CREATE TABLE [dbo].[Sales_2NF]
(
	[SaleId] INT NOT NULL IDENTITY(1,1), 
	[SaleDate] DATE NOT NULL, 
	[CustomerId] INT NOT NULL, 
	[ProductId] INT NOT NULL, 
	[Quantity] INT NOT NULL, 
	[SpecialHandlingNotes] NVARCHAR(500) NULL,
	[LastName] NVARCHAR(50) NOT NULL, 
	[FirstName] NVARCHAR(50) NOT NULL, 
	[Address1] NVARCHAR(250) NOT NULL, 
	[Address2] NVARCHAR(250) NULL, 
	[City] NVARCHAR(50) NOT NULL, 
	[State] NCHAR(2) NOT NULL, 
	[Zip] NCHAR(6) NOT NULL,
	[CustomerHomePhone] NCHAR(10) NULL, 
	[CustomerMobilePhone] NCHAR(10) NULL, 
	[CustomerOtherPhone] NCHAR(10) NULL,
	CONSTRAINT [PK_Sales_2NF] PRIMARY KEY ([SaleId]),
)
